@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Test-RDF-DOAP-Version/project>
	deps:runtime-requirement         [ deps:on "Test::More"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "URI::Escape"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "RDF::TriN3 0.202"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "RDF::Trine 0.135"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

